# Verilator creates a obj_dir,
# LANGUAGE
LDH         = sv
# MODULES
RTL_PATH    = rtl/
TOP_MODULE  = mod_main
INCLUDES    = $(RTL_PATH)/include
# Add the extra modules here
MODULES    +=
SRC_FILES   = $(addsuffix .$(LDH), $(TOP_MODULE) $(MODULES))
VSRC        = $(addprefix $(RTL_PATH), $(SRC_FILES))
#MODULES    +=
# TEST BENCH
EXT         = cpp
TEST_BENCH  = tb_$(TOP_MODULE)
#SOME FLAGS FOR TRACE WAVES
TRACE       = --trace --x-assign unique --x-initial unique
TRACE      += --trace-structs --structs-packed --trace-threads 4
TRACE      += --no-trace-top --trace-max-array "64"
# RTLVIEWER
# QUARTUS TOOLS
QSRC        = $(addprefix --source=, $(SRC_FILES))
QUARTUS_MAP = /opt/intelFPGA/23.1/quartus/bin/quartus_map
QUARTUS_NPP = /opt/intelFPGA/23.1/quartus/bin/quartus_npp
QNUI        = /opt/intelFPGA/23.1/quartus/bin/qnui
FAMILY      = "MAX 10"
DEVICE      = 10M50DAF484C6G
FPGA        = --family=$(FAMILY) --part=$(DEVICE)
QFILES_OPT  = --read_settings_files=on --write_settings_files=off

all: lint verilating

lint : $(VSRC)
	@echo
	@echo "### CHECKING ERRORS ###"
	verilator -Wall --lint-only --hierarchical $^ --top-module $(TOP_MODULE) -y $(INCLUDES)

verilating : $(VSRC)
	@echo
	@echo "### VERILATING ###"
	verilator -Wall $(TRACE) -cc --hierarchical $^ --top-module $(TOP_MODULE) -y $(INCLUDES) --exe tb_sim/*.$(EXT)
	@touch .stamp.verilate

build : .stamp.verilate
	@echo
	@echo "### BUILDING SIM ###"
	make -j `nproc` -C obj_dir -f V$(TOP_MODULE).mk V$(TOP_MODULE)

tb_sim/waveform.vcd : ./obj_dir/V$(TOP_MODULE)
	@echo
	@echo "### SIMULATING ###"
	$^ +verilator+rand+reset+0

sim : tb_sim/waveform.vcd
	@echo
	@echo "### WAVES ###"
	gtkwave $^ -a gtkwave_setup.gtkw

run : build sim

ys : rtl.ys
	@echo "### SIMPLE RTL ###"
	yosys $^

synth : $(RTL_PATH)
	rm -rf qfiles/
	mkdir -p qfiles
	@echo
	@echo "#### ANALYSIS & SYNTHESIS ####"
	$(QUARTUS_MAP) $(TOP_MODULE) -c $(TOP_MODULE) -l $^ --lib_path=$(INCLUDES) --parallel=4 $(FPGA) $(QFILES_OPT) $(QSRC)
	@echo
	@echo "#### SAVE FILES ####"
	mv db qfiles
	mv incremental_db qfiles
	mv $(TOP_MODULE).* qfiles

net :
	@echo
	@echo "#### GENERATE NETLIST ####"
	$(QUARTUS_NPP) qfiles/$(TOP_MODULE) --netlist_type=sgate

view :
	@echo
	@echo "#### SUMMARY ####"
	cat qfiles/$(TOP_MODULE).map.summary
	@echo
	@echo "#### OPEN RTL VIEWER ####"
	$(QNUI) qfiles/$(TOP_MODULE)

qrtl :  synth net view

help:
	@echo "### HELP ###"
	@echo "make       -> Check for errors in the codes, and start the "verilating" process as well as look for errors in the test bench."
	@echo "make run   -> Creates the executable, runs the simulation and displays the generated waves in GTKWave."
	@echo "make synth -> Synthesis and analysis with Intel® tools."
	@echo "make net   -> Generar Netlist con herramientas Intel®."
	@echo "make view  -> Open RTLViewer by Intel® to view the schematic diagram. "
	@echo "make qrtl  -> Do Analysis and Synthesis, Generate Netlist, and open the RTLViewer, all with Intel tools."
	@echo "make ys    -> Create simple RTL deagram with Yosys tool."
	@echo "make clean -> Deletes all files generated by Verilator & Intel tools and by the executable."
	@echo "make help  -> Show a short description of the commands "

clean:
	@echo "### CLEAN ###"
	rm -rf obj_dir/
	rm -rf qfiles/
	rm -rf .stamp.*
	rm -rf *.plist
	rm -rf tb_sim/waveform.vcd
